import type { Metadata } from "next";
import "../globals.css";
import "katex/dist/katex.min.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Wiqi",
  description: "Generated by blood, sweat and tears",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <meta charSet="utf-8" />
        <title>wiqi</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="flex flex-col h-screen">
        <NextIntlClientProvider messages={messages}>
          <div className="flex-grow">{children}</div>
        </NextIntlClientProvider>
        <footer className="bg-slate-700 px-3 py-3">
          <p className="text-xs">
            © 2024, Built with ❤️ by PushQuantum for Humans
          </p>
        </footer>
      </body>
    </html>
  );
}
