on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  formatting_check:
    name: formatting_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun prettier -c ./
      - run: bun run build
